# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "base"
  config.vm.network :forwarded_port, guest: 5000, host: 8081

  config.vm.provision :chef_solo do |chef|

    chef.add_recipe "apt"
    chef.add_recipe("openssl")
    chef.add_recipe("vim")

    chef.add_recipe("git")
    chef.add_recipe("curl")

    chef.add_recipe("build-essential")

    chef.add_recipe("nodejs")

  end

end
